name: Test and lint
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --select=E9,F63,F7,F82 --show-source
        flake8 --exit-zero --max-complexity=10
    - name: Check with Isort
      run: |
        pip install isort
        isort --check -rc -sp setup.cfg .
    
    - name: Sort with Isort
      if: failure()
      run: |
        isort -y -rc -sp setup.cfg .
    
    - name: Create Pull Request
      if: failure()
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }})
        branch: actions/auto
        commit-message: Changes done by tests
        title: Linter changed files
        labels: report, automated pr
        assignees: ${{github.event.repository.owner.name}}
        reviewers: ${{github.event.repository.owner.name}}